### ISSUE TITLE
Failed to activate the atom-underscore package

### ISSUE THREAD

**Issue by princenaman** [dborstelmann/atom-underscore#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.1
**Thrown From**: [atom-underscore](https://github.com/dborstelmann/atom-underscore) package 0.1.3

### Stack Trace

Failed to activate the atom-underscore package

```
At Cannot find module 'undefined/node_modules/first-mate/lib/grammar.js'

Error: Cannot find module 'undefined/node_modules/first-mate/lib/grammar.js'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-underscore/lib/atom-underscore.js:1:166)
    at /packages/atom-underscore/lib/atom-underscore.js:207:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:220:40)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/src/package.js:200:20)
    at Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:862:28)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:867:27)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-bootstrap4 1.4.0 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
atom-typescript 12.1.2 
atom-underscore 0.1.3 
autocomplete-nunjucks 0.5.0 
autocomplete-onsenui 0.1.1 
autocomplete-php 0.3.7 
busy-signal 1.4.3 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
file-icons 2.1.16 
hyperclick 0.1.5 
intentions 1.1.5 
js-hyperclick 1.13.0 
language-babel 2.84.0 
language-blade 0.38.0 
language-ejs 0.4.0 
language-javascript-jsx 0.3.7 
language-nunjucks 4.2.1 
language-vue 0.23.1 
laravel-snippets 2.1.0 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.6.10 
php-hyperclick 1.2.1 
symbol-gen 1.3.1 
uglify 1.3.1 
underscorejs-snippets 0.2.2 
vue2-autocomplete 0.1.0-alpha.4 
```

**Comment by andres-lowrie** [comment]
This issue is also preset with beta on Ubuntu fyi 

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.0-beta1 x64
**Electron**: 1.7.11
**OS**: Ubuntu 18.04
**Thrown From**: [atom-underscore](https://github.com/dborstelmann/atom-underscore) package 0.1.3


### Stack Trace

Failed to activate the atom-underscore package

```
At Cannot find module 'undefined/node_modules/first-mate/lib/grammar.js'

Error: Cannot find module 'undefined/node_modules/first-mate/lib/grammar.js'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/usr/share/atom-beta/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom-beta/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/usr/share/atom-beta/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-underscore/lib/atom-underscore.js:1:166)
    at /packages/atom-underscore/lib/atom-underscore.js:207:3)
    at Module.get_Module._compile (/usr/share/atom-beta/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom-beta/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/usr/share/atom-beta/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/usr/share/atom-beta/resources/app/src/package.js:782:33)
    at Package.activateNow (/usr/share/atom-beta/resources/app/src/package.js:220:40)
    at measure (/usr/share/atom-beta/resources/app/src/package.js:206:33)
    at Package.measure (/usr/share/atom-beta/resources/app/src/package.js:88:25)
    at activationPromise.Promise (/usr/share/atom-beta/resources/app/src/package.js:200:20)
    at Promise (<anonymous>)
    at Package.activate (/usr/share/atom-beta/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/usr/share/atom-beta/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/usr/share/atom-beta/resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (/usr/share/atom-beta/resources/app/src/config.js:866:28)
    at PackageManager.activatePackages (/usr/share/atom-beta/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/usr/share/atom-beta/resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (/usr/share/atom-beta/resources/app/src/atom-environment.js:871:27)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-beautify 0.32.4 
atom-handlebars 1.3.0 
atom-mocha-snippets 0.6.3 
atom-ternjs 0.18.3 
atom-underscore 0.1.3 
busy-signal 1.4.3 
copy-find-results 0.1.0 
cursor-history 0.13.1 
docblockr 0.13.7 
dockerletion 0.2.0 
easy-motion-redux 1.1.1 
emmet 2.4.3 
es6-snippets 0.3.0 
ex-mode 0.18.0 
git-blame 1.6.0 
git-time-machine 2.0.1 
go-debug 1.6.2 
go-plus 5.8.3 
go-signature-statusbar 1.2.3 
hard-wrap 1.7.1 
hey-pane 1.1.0 
hyperclick 0.1.5 
intentions 1.1.5 
js-hyperclick 1.13.0 
language-docker 1.1.8 
language-rust 0.4.12 
language-svg 0.9.2 
language-vue 0.23.1 
linter 2.2.0 
linter-csslint 2.0.1 
linter-docker 0.3.2 
linter-eslint 8.4.1 
linter-rust 0.8.5 
linter-sass-lint 1.8.3 
linter-tslint 1.9.1 
linter-ui-default 1.7.1 
maximize-panes 0.2.0 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
octocat-syntax 2.2.1 
open-this 0.5.0 
prettier-atom 0.53.0 
racer 0.20.0 
relative-numbers 0.9.0 
spacemacs-evil-keys 0.2.0 
svg-preview 0.12.1 
todo-show 2.3.0 
vim-mode-plus 1.32.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
vim-mode-plus-move-to-symbols 0.5.0 
vue-snippets 0.6.0 
Zen 0.18.0 
zentabs 0.8.9 
```

**Comment by princenaman** [comment]
Update?

**Comment by bdward16** [comment]
Having the same issue

**Comment by thaddeusalbers** [comment]
workaround:
edit 
`.atom/packages/atom-underscore/lib/atom-underscore.js`
and change the first line to:
`Grammar = require(atom.getLoadSettings().resourcePath + '/node_modules/first-mate/lib/grammar.js');
`

hat tip to https://github.com/sveale/remote-edit/issues/243#issuecomment-391681839
