### ISSUE TITLE
Failed to load the atom-underscore package

### ISSUE THREAD

**Issue by cyberbit** [dborstelmann/atom-underscore#6]
[Enter steps to reproduce:]

1. Attempt to install atom-underscore

**Atom**: 1.26.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-underscore](https://github.com/dborstelmann/atom-underscore) package 0.1.3

### Stack Trace

Failed to load the atom-underscore package

```
At Cannot find module 'undefined/node_modules/first-mate/lib/grammar.js'

Error: Cannot find module 'undefined/node_modules/first-mate/lib/grammar.js'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.26.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (<embedded>:12204:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (<embedded>:11548:33)
    at /packages/atom-underscore/lib/atom-underscore.js:1:166)
    at /packages/atom-underscore/lib/atom-underscore.js:207:3)
    at Module.get_Module._compile (<embedded>:11588:36)
    at Object.value [as .js] (<embedded>:11840:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (<embedded>:96:26)
    at Package.requireMainModule (<embedded>:73089:33)
    at measure (<embedded>:72450:22)
    at Package.measure (<embedded>:72395:25)
    at Package.load (<embedded>:72436:16)
    at PackageManager.loadAvailablePackage (<embedded>:25677:16)
    at PackageManager.loadPackage (<embedded>:25610:25)
    at PackageManager.activatePackage (<embedded>:25748:23)
    at <embedded>:56238:35
    at exit (<embedded>:55875:22)
    at triggerExitCallback (<embedded>:130422:15)
    at ChildProcess.process.on (<embedded>:130452:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

```

### Commands

```
     -1:41 core:undo (input.hidden-input)
     -1:39.2.0 editor:consolidate-selections (input.hidden-input)
     -1:39.2.0 core:cancel (input.hidden-input)
     -1:39.1.0 editor:consolidate-selections (input.hidden-input)
     -1:39.1.0 core:cancel (input.hidden-input)
     -1:36.1.0 intentions:highlight (input.hidden-input)
     -1:36.1.0 core:copy (input.hidden-input)
     -1:34.3.0 intentions:highlight (input.hidden-input)
     -1:34.2.0 core:paste (input.hidden-input)
     -1:27.1.0 intentions:highlight (input.hidden-input)
     -1:27 core:save (input.hidden-input)
     -1:22.8.0 intentions:highlight (input.hidden-input)
     -1:22.8.0 core:copy (input.hidden-input)
     -1:07.8.0 intentions:highlight (input.hidden-input)
     -1:07.8.0 find-and-replace:show (input.hidden-input)
  2x -1:01.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.32.2 
atom-ide-ui 0.11.1 
atom-underscore 0.1.3 
autoclose-html 0.23.0 
autocomplete-javascript 0.0.2 
busy-signal 1.4.3 
docblockr 0.13.7 
emmet 2.4.3 
file-icons 2.1.19 
git-plus 7.10.2 
highlight-selected 0.13.1 
ide-php 0.7.14 
intentions 1.1.5 
language-blade 0.39.0 
language-dotenv 1.1.1 
language-nginx 0.8.0 
linter 2.2.0 
linter-phpcs 1.6.8 
linter-ui-default 1.7.1 
minimap 4.29.8 
php-integrator-base 3.3.0 
project-manager 3.3.5 
```

**Comment by princenaman** [comment]
Same I guess.
https://github.com/dborstelmann/atom-underscore/issues/5
